# V1.0

In [1]:
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline
from gridworld_env import GridworldEnv
import matplotlib.pyplot as plt
import matplotlib.animation as animation
from algorithms.MultiDistral.MultiDistral import MultiDistral

def updatefig(j):
    # set the data in the axesimage object
    im.set_array(env.grid_images[j])
    # return the artists set
    return [im]

In [2]:
from algorithms.MultiDistral.MultiDistral_E_step.Soft_Q_Learning_without_rollout import Soft_without_rollout
# Q learning params
ALPHA = 0.1 # learning rate
GAMMA = 0.99 # reward discount
TAU=0.5
LEARNING_COUNT = 300
TEST_COUNT = 100

TURN_LIMIT = 100
v1=MultiDistral( TURN_LIMIT, ALPHA, GAMMA, TAU,Soft_without_rollout)

v1.optimise(2)

/Users/samueloliveira/opt/anaconda3/envs/maai-env/lib/python3.12/site-packages/gym/spaces/box.py:127: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(f"Box bound precision lowered by casting to {self.dtype}")


[0.20009546 0.2002654  0.20005758 0.19853939 0.20104215]
[0.1959785  0.19597922 0.19598931 0.20602651 0.20602651]
[0.20013417 0.19927809 0.20019364 0.20123594 0.1991582 ]
[0.1959785  0.19597922 0.19598931 0.20602651 0.20602651]
[0.20040375 0.19940422 0.20040375 0.20040375 0.19938451]
[0.2 0.2 0.2 0.2 0.2]
[0.20009546 0.2002654  0.20005758 0.19853939 0.20104215]
[0.2 0.2 0.2 0.2 0.2]
[0.19915518 0.2002112  0.2002112  0.2002112  0.2002112 ]
[0.2 0.2 0.2 0.2 0.2]
[0.19998467 0.1990737  0.20102842 0.19998467 0.19992858]
[0.2 0.2 0.2 0.2 0.2]
[0.19998467 0.1990737  0.20102842 0.19998467 0.19992858]
[0.2 0.2 0.2 0.2 0.2]
[0.19955759 0.19961575 0.20063618 0.20063618 0.1995544 ]
[0.2 0.2 0.2 0.2 0.2]
[0.19916993 0.2002075  0.2002075  0.2002075  0.2002075 ]
[0.2 0.2 0.2 0.2 0.2]
[0.20020774 0.20020774 0.19916901 0.20020774 0.20020774]
[0.2 0.2 0.2 0.2 0.2]
[0.2 0.2 0.2 0.2 0.2]
[0.2 0.2 0.2 0.2 0.2]
[0.19918546 0.20020363 0.20020363 0.20020363 0.20020363]
[0.2 0.2 0.2 0.2 0.2]
[0.2 0.2 0.2 0.2 

/Users/samueloliveira/Documents/Masters/MAAI/multi-agent_distral/algorithms/MultiDistral/MultiDistral_E_step/Soft_Q_Learning_without_rollout.py:53: RuntimeWarning: divide by zero encountered in log
  log_action_probs = self.psi*np.log(self.pi_0_2[tuple(state)])+(self.beta*advantages)
/Users/samueloliveira/Documents/Masters/MAAI/multi-agent_distral/algorithms/MultiDistral/MultiDistral_E_step/Soft_Q_Learning_without_rollout.py:54: RuntimeWarning: invalid value encountered in divide
  probs=np.exp(log_action_probs)/np.sum(np.exp(log_action_probs))


ValueError: probabilities contain NaN